export const DOMAINS = [
    // Gmail-style
    { pretty: 'gmail-inbox.me', real: 'king-tmail.tech' },
    { pretty: 'gmail-fast.com', real: 'king-tmail.tech' },
    { pretty: 'gmail-secure.net', real: 'king-tmail.tech' },
    { pretty: 'gmail-temp.org', real: 'king-tmail.tech' },
    { pretty: 'gmail-drop.me', real: 'king-tmail.tech' },
    { pretty: 'gmail-safe.com', real: 'king-tmail.tech' },
    { pretty: 'gmail-quick.net', real: 'king-tmail.tech' },
    { pretty: 'gmail-box.org', real: 'king-tmail.tech' },
    { pretty: 'gmail-shield.me', real: 'king-tmail.tech' },
    { pretty: 'gmail-pro.com', real: 'king-tmail.tech' },
    
    // Edu-style
    { pretty: 'student-mail.edu.pl', real: 'x@u.king-tmail.tech' },
    { pretty: 'campus-inbox.edu.es', real: 'x@u.king-tmail.tech' },
    { pretty: 'uni-mail.edu.it', real: 'x@u.king-tmail.tech' },
    { pretty: 'college-box.edu.co', real: 'x@u.king-tmail.tech' },
    { pretty: 'alumni-mail.edu.br', real: 'x@u.king-tmail.tech' },
    { pretty: 'academy-inbox.edu.mx', real: 'x@u.king-tmail.tech' },
    { pretty: 'scholar-mail.edu.ar', real: 'x@u.king-tmail.tech' },
    { pretty: 'faculty-box.edu.pe', real: 'x@u.king-tmail.tech' },
    { pretty: 'student-inbox.edu.vn', real: 'x@v.king-tmail.tech' },
    { pretty: 'campus-mail.edu.ph', real: 'x@v.king-tmail.tech' },
    
    // Outlook-style
    { pretty: 'outlook-inbox.me', real: 'x@v.king-tmail.tech' },
    { pretty: 'outlook-fast.com', real: 'x@v.king-tmail.tech' },
    { pretty: 'outlook-secure.net', real: 'x@v.king-tmail.tech' },
    { pretty: 'outlook-temp.org', real: 'x@v.king-tmail.tech' },
    { pretty: 'outlook-drop.me', real: 'x@v.king-tmail.tech' },
    { pretty: 'outlook-safe.com', real: 'x@v.king-tmail.tech' },
    { pretty: 'outlook-quick.net', real: 'x@i.king-tmail.tech' },
    { pretty: 'outlook-box.org', real: 'x@i.king-tmail.tech' },
    { pretty: 'outlook-shield.me', real: 'x@i.king-tmail.tech' },
    { pretty: 'outlook-pro.com', real: 'x@i.king-tmail.tech' },
    
    // Other professional
    { pretty: 'secure-gate.com', real: 'x@i.king-tmail.tech' },
    { pretty: 'mail-fast.com', real: 'x@i.king-tmail.tech' },
    { pretty: 'temp-box.net', real: 'x@i.king-tmail.tech' },
    { pretty: 'quick-mail.org', real: 'x@i.king-tmail.tech' },
    { pretty: 'inbox-pro.me', real: 'x@e.king-tmail.tech' },
    { pretty: 'mail-shield.com', real: 'x@e.king-tmail.tech' },
    { pretty: 'safe-inbox.net', real: 'x@e.king-tmail.tech' },
    { pretty: 'temp-mail.org', real: 'x@e.king-tmail.tech' },
    { pretty: 'fast-inbox.me', real: 'x@e.king-tmail.tech' },
    { pretty: 'mail-drop.com', real: 'x@e.king-tmail.tech' },
    { pretty: 'quick-box.net', real: 'x@e.king-tmail.tech' },
    { pretty: 'inbox-safe.org', real: 'x@e.king-tmail.tech' },
    { pretty: 'mail-temp.me', real: 'x@l.king-tmail.tech' },
    { pretty: 'secure-inbox.com', real: 'x@l.king-tmail.tech' },
    { pretty: 'fast-mail.net', real: 'x@l.king-tmail.tech' },
    { pretty: 'temp-drop.org', real: 'x@l.king-tmail.tech' },
    { pretty: 'quick-inbox.me', real: 'x@l.king-tmail.tech' },
    { pretty: 'inbox-fast.com', real: 'x@l.king-tmail.tech' },
    { pretty: 'mail-safe.net', real: 'x@l.king-tmail.tech' },
    { pretty: 'secure-box.org', real: 'x@l.king-tmail.tech' }
];
