export const DOMAINS = [
    // Gmail-style
    { pretty: 'gmail-inbox.me', real: 'king-tmail.tech' },
    { pretty: 'gmail-fast.com', real: 'king-tmail.tech' },
    { pretty: 'gmail-secure.net', real: 'king-tmail.tech' },
    { pretty: 'gmail-temp.org', real: 'king-tmail.tech' },
    { pretty: 'gmail-drop.me', real: 'king-tmail.tech' },
    { pretty: 'gmail-safe.com', real: 'king-tmail.tech' },
    { pretty: 'gmail-quick.net', real: 'king-tmail.tech' },
    { pretty: 'gmail-box.org', real: 'king-tmail.tech' },
    { pretty: 'gmail-shield.me', real: 'king-tmail.tech' },
    { pretty: 'gmail-pro.com', real: 'king-tmail.tech' },
    
    // Edu-style
    { pretty: 'student-mail.edu.pl', real: 'x@u.king-tmail.tech' },
    { pretty: 'campus-inbox.edu.es', real: 'x@u.king-tmail.tech' },
    { pretty: 'uni-mail.edu.it', real: 'x@u.king-tmail.tech' },
    { pretty: 'college-box.edu.co', real: 'x@u.king-tmail.tech' },
    { pretty: 'alumni-mail.edu.br', real: 'x@u.king-tmail.tech' },
    { pretty: 'academy-inbox.edu.mx', real: 'academy-real.mx' },
    { pretty: 'scholar-mail.edu.ar', real: 'scholar-real.ar' },
    { pretty: 'faculty-box.edu.pe', real: 'faculty-real.pe' },
    { pretty: 'student-inbox.edu.vn', real: 'student-real.vn' },
    { pretty: 'campus-mail.edu.ph', real: 'campus-real.ph' },
    
    // Outlook-style
    { pretty: 'outlook-inbox.me', real: 'out-real.me' },
    { pretty: 'outlook-fast.com', real: 'out-fast.com' },
    { pretty: 'outlook-secure.net', real: 'out-secure.net' },
    { pretty: 'outlook-temp.org', real: 'out-temp.org' },
    { pretty: 'outlook-drop.me', real: 'out-drop.me' },
    { pretty: 'outlook-safe.com', real: 'out-safe.com' },
    { pretty: 'outlook-quick.net', real: 'out-quick.net' },
    { pretty: 'outlook-box.org', real: 'out-box.org' },
    { pretty: 'outlook-shield.me', real: 'out-shield.me' },
    { pretty: 'outlook-pro.com', real: 'out-pro.com' },
    
    // Other professional
    { pretty: 'secure-gate.com', real: 'real-secure.com' },
    { pretty: 'mail-fast.com', real: 'fast-real.com' },
    { pretty: 'temp-box.net', real: 'box-real.net' },
    { pretty: 'quick-mail.org', real: 'real-quick.org' },
    { pretty: 'inbox-pro.me', real: 'pro-real.me' },
    { pretty: 'mail-shield.com', real: 'shield-real.com' },
    { pretty: 'safe-inbox.net', real: 'safe-real.net' },
    { pretty: 'temp-mail.org', real: 'mail-real.org' },
    { pretty: 'fast-inbox.me', real: 'fast-real.me' },
    { pretty: 'mail-drop.com', real: 'drop-real.com' },
    { pretty: 'quick-box.net', real: 'quick-real.net' },
    { pretty: 'inbox-safe.org', real: 'safe-real.org' },
    { pretty: 'mail-temp.me', real: 'temp-real.me' },
    { pretty: 'secure-inbox.com', real: 'secure-real.com' },
    { pretty: 'fast-mail.net', real: 'fast-real.net' },
    { pretty: 'temp-drop.org', real: 'drop-real.org' },
    { pretty: 'quick-inbox.me', real: 'quick-real.me' },
    { pretty: 'inbox-fast.com', real: 'fast-real.com' },
    { pretty: 'mail-safe.net', real: 'safe-real.net' },
    { pretty: 'secure-box.org', real: 'box-real.org' }
];
